micronaut:
  server:
    port: ${SERVER_PORT:8081}
  application:
    name: micronautQuickstart
netty:
  default:
    allocator:
      max-order: 3
hello:
  world:
    message: Hello World from application.yml
    translation:
      cz: "Ahoj Světe"
      en: "Hello World"
